server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 6b20fabe-8973-43ba-858e-4dccc9d1b62b
    gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/admin/hosp/**,/api/hosp/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/admin/user/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/admin/cmn/**
  profiles:
    active: dev
